= Type Conversion, Type Aliases, and Type Deduciton

== Floating-point and integral promotion

=== What is a numeric promotion?

A numeric promotion is a specific kind of implicit type conversion where certain smaller numeric types are converted to certain larger numeric types.

**Numeric promotion PRESERVES THE VALUE**

The destination type can represent the original value wihtout losing its information

For example:
[source,cpp]
--
float x{ 5.0f };

void printDouble(double value)
{
    std::cout << value;
}

printDouble(x);
--

Here the void function print double requires a double value, so C++ implicitly promotes float 5.0 to double 5.0

The value remains the same, only its type/representation changes

Numeric promotions are useful partly because CPUs tend to eprform operations most naturally on certain fundamental types, and because promotions let smaller types work in contexts expecting those types without requiring separate implenetaitons for every small numeric type.

==== Two types of numeric promotion

There are two kinds of numeric promotion:

* Floating point promotion
* Integral promotion

===== Floating point promotion

Floating point promotion is simple:
    A float can be promoted to a double while preserving its value.

For example:
[source,cpp]
--
float f{ 3.5f };
double d{ f };
--

Conceptually, the d now stores the double version of 3.5 whereas the f stores the float version of 3.5. This is a promotion, not merely a generic conversion.

===== Integral promotion

Integral promotion applies to samller integral types such as char, short, and bool.

They are generally promoted to int if int can represent all possible values of the original type.

Examples include:
char  → int
short → int
bool  → int

For bool:
false → 0
true  → 1

So this works:
void printInt(int x)
{
    std::cout << x;
}

short s{ 5 };
printInt(s);

C++ promotes the short value to an int before passing it into the function.

====== Why integral promotions exist

Smaller integral types such as char and short aren't necessarily the types the CPU most naturally performs arithmetic with. 

Promoting them to int allows C__ operations using a more natural type.

It also means functions that accept int can accept values from several smaller integral types through promotion rather than requiring separate functions for ecah type.

=== Not every convesion to a larger type is a promotion

A promotion is a specific set of conversions defined by C++. it does not simply mean: "The destination type is bigger."

For example:
short → int       promotion
float → double    promotion

int → long        not a promotion
char → short      not a promotion

The latter conversions may sitll be legal implicit conversions, but they're classified as numeric conversions.

=== overview


Numeric promotion
    = specific kind of implicit conversion
    = value-preserving

Two kinds:

Floating-point promotion:
    float → double

Integral promotion:
    small integral types → usually int

"Promotion" does NOT simply mean
"convert to a larger type."

== Numeric conversions

=== What is a numeric conversion

If a conversion is already classified as a numeric promotion, we don't call it a numeric conversion.

So:

short → int | an integral promotion

But:
int → short
int → long
short → char

Are numeric conversions

The big difference from promtion is:

Numeric promotions are always value preserving. Numeric conversions are not necessarily value-preserving.

=== The five kinds of numeric conversions

LearnCpp gives five basic categories

Integral to another integral type:
[source,cpp]
--
short s = 3;       // int → short
long l = 3;        // int → long
char c = s;        // short → char
--
Integral promotions dont count here.

Floating point to another floating point type:
[source,cpp]
--
float f = 3.0;          // double → float
long double ld = 3.0;   // double → long double
--
Again, floating point promotions dont count here.

Floating point to integral and vice versa:
[source,cpp]
--
int x = 3.5; // double → int
double x = 3; // int to double
--

and integral/floating point to bool:
[source,cpp]
--
bool a = 3;
bool b = 3.0;
--

=== Numeric conversions can be safe or unsafe

There are three saftey categories we will divide numeric conversions into

==== Value preserving conversions

A value preserving conversion means that the destination type can represent the source value exactly

For instance:
[source,cpp]
--
int x{ 5 };
long y = x;
--

You would get int 5 to long 5. Nothing meaningful changed except for the type.

Another example:
[source,cpp]
--
short s{ 5 };
double d = s;
--

Here the short 5 becomes double 5.0. The value is still exactly as represented. These are considered safe conversions.

==== Reinterpretive conversions

This one is mostly about signed to unsigned conversions

For example:
[source,cpp]
--
int x{ 5 };
unsigned int y{ x };
--

This is no problem, since signed 5 is the same as unsigned 5.

However...
[source,cpp]
--
int x{ -5 };
unsigned int y{ x };
--

this is different because an unsigned integer cannot represent -5.

The conversion then produces a large unsigned value instead

This is called reinterpretive because the resulting value can change even though the underlying information isn't necessarily lost, youc an convert it back and recover the original value under the defined conversion behavior.

==== Lossy conversions

A lossy conversion is one where information can actually diappear.

For example:
[source,cpp]
--
double x{ 3.5 };
int y = x;
--

This double, when converted to an integer, loses 0.5. If you later convert the double back to an integer, you would get 3.0, NOT 3.5. This means the part of the data has been lost.

===== Floating poitn covnersions can lose precision

When you are convertin a double to a float, you can lose some precision in the value.

For example:
[source,cpp]
float x = 1.23456789;

May become approximately

1.234567

Since the destination dosent have enough precision to retain everything from the original value.

=== Range matters

A huge general rule is that the destination type hsa to be capabale of representing the value youre giving it if you want the conversion to behave as expected.

For example if I convert variable x  of type int with a value of 2 to type short, thats fine, since short can fit easily inside a short.

But converting some enormous integer to a tiny type like char can produce an unexpected result because that value isnt representable by the destination type.

=== Integral to floating point conversions

These generally behave as youd expect when the floating point type can represent that value. For example 10 converted to a float would just be 10.0

However, sufficiently large integers may not be represented by a floating point type because floating point types have limited percision.

=== Floating point to integral conversions

Converting a floating point to an integer may cause a loss of data. For instance converting float 3.9 to an integer would turn it into 3, not 4, losing .9 data. The fractional componenet is discarded, not rounded.

== Narrowing conversions, list initialization, and constexpr initializers

=== What is a narrowing conversion?

A narrowing ocnversion is  apotentially unsafe numeric conversion where the destinationt type may not be capabale of repsentating all possible values of the soucrce type.

For example:
[source,cpp]
--
double d{ 3.5 };
int x = d;
--

int cant represent fractional values, so double to int is narrowing.

The important word is potentially unsafe. A particular value would make this work, such as converting double 5.0 to an integer wouldnt change the value.

=== What conversions are considered narrowing.

Generally there is a pattern:
floating-point → integral
    double → int

larger/higher-ranked floating-point → smaller/lower-ranked floating-point
    double → float

integral → floating-point
    int → float
    (when exact representation isn't guaranteed)

integral → integral type that can't represent all source values
    int → short
    signed → unsigned
    etc.

The general mental model is this:

If changing types could cause the value to become unrepresentable or lose information, C++ may classify the conversion as narrowing.

=== Avoid implicit narrowing conversions

Because narrowing conversions can be dangerous, LearnCPP reccomends avodiing them when possible.

If you actually intend to narrow something, make that intention explicit with a static_cast instead of relying on it implicity:

[source,cpp]
--
void printInt(int x)
{
}

double d{ 5.0 };

printInt(static_cast<int>(d));
--

here we intentionally transform the double into an int via static cast instead of relying on it to be implicitly converted.

=== Brace initialization protects you from narrowing

Brace/list initialization is this:
[source,cpp]
--
int x{3.5};
--

If you did this, it *would not compile*

Why?

double 3.5
   ↓
int
   ↓
narrowing conversion
   ↓
{} says NO

C++ made list initialization reject narrowing conversions. This is one of the major reasons why you should use it always.

=== constexpr can make some otherwise narrowing conversions safe

Normally, if the value is only known at runtime, the compiler cannot know whether a conversion will preserve the value.

For instance:

[source,cpp]
--
int n{};
std::cin >> n;

unsigned int u{n};
--

This fails because n is determined at runtime. The compiler dosen't know whether itll contain some representable by unsigned int.

But if the value is a constant expression, the compiler knows the value during compilation.

For certain conversions that would ordinarily be considered narrowing, C++ makes an exception when:

the source is a constant expression AND the actual value can be represented by the destination type.

So the distinction is basically "Can the destination represent every possible value of this source type" vs "Can the destination represent this specific value that I already know?"

=== list initialization with constexpr initializers

The constexpr exceptions make list initialization practical because ltierals are constant expressions. This means the compiler knows their values and can allow conversions that would otherwise potentially be narrowing when the particular value satisfies the exception.

For example, you can initialize an unsigned int with 5 without writing 5u, intiialize a float with 1.5 without writing 1.5f, or initialize a short with 5 without needing a static_cast. This also applies to copy and direct intitialization, not just brace initialization.

However, floating-point conversions can still initialize a lower ranked floating point type as long as the value is within that type's range, even if precision is lost.

Floating point rank goes:

long double to double to float

So something like a double literal initializing a float can be legal despite losing precision. 

== Arithmetic conversions

=== What are arithmetic conversions?

When you use a binary arithmetic operator such as +, -, /, or %, C++ generally needs the operands to have compatible types before performing the operation

If they have different types, C++ implicitly converts one or both operands to a common type. these are called usual arithmetic conversions.

For example, with an int and a double, the int is converted to double, then the operation happens using two doubles. The result is therefore, also a double.

=== The usual arithmetic conversion rules

. If either operand is a floating type, C++ generally converts the lower ranked operand to the higher ranked floating point type:

int + double to double + double
float + double to double + double

. If both operands are integral types, C++ first applies integral promotions to them.

. If the promoted integral types still differ, C++ finds a common type based mainly on their ranked and signedness, then converts as necessary.

=== Signed and unsigned integers

Mixed signed and unsigned integers can cause suprising results

If C++ chooses an unsigned type as the common type, a negative signed value may be covnerted to an unsigned value before the operation occurs.

So expressions involving something like:
[source,cpp]
--
int x{ -3 };
unsigned int y{ 5 };

x < y
--

=== std::common_type and std::common_type_t

std::common is a type trait that determines a commont ype that all specified types can be implicitly converted to.

For instance, the common type between int and double is double, since an int can be converted to a double.

So the snippet of code:
`std::common_type<int, double>::type`

the resulting type is accessed through the nested ::type.

std::common_type_t is simply a convenience alias introduced so you dont have to write ::type.

== Explicit Type Conversion

=== Implicit vs explicit

An implicit type conversion happens automatically when C++ converts a value from one type to antother, whereas an explicit type conversion, or cast, happens when you specifically tell Cpp to convert a value to another type.

This is useful when the type of an expression affects how an operation behaves

=== Type of casts

C++ has find kinds of casts:
- static_cast
- dynamic_cast
- const_cast
- reinterpret_cast
- C-style casts

The first four are called named casts

- For now, static_cast is the important one. dynamic_cast comes much later with inheritance, and then usually people avoid the other two unless they have a specific reason.

==== C-style casts

C-style syntax looks like:
`(double)x`

There is also function style syntax:

`double(x)`

For example:
`std::cout << (double)x/y;`

This worlks, but C-style casts generally should be avoided since the C-style cast can perform several different kinds of conversions, including potentially unsafe ones. Looking at the syntax dosen't clearly tell you what kind of conversion is happening.

Named casts are more explicit, easier to identify/search for, and more restricted in what they're allowed to do.

==== static_cast

static_cast is the primary cast to use when you deliberatly want to convert a value to another type.

Syntax:
`static_cast<target_type>(expression)`

Example:
[source,cpp]
--
int x {10};

static_cast<double>(x)
--

This produces a temporary double containing 10.0, and more importantly, it does not change x itself. x reamins an int; you're producing a converted value FROM x.

===== Using static_cast for narrowing conversions

a narrowing conversion converts to a type that may not eb able to represent the original value safely

[source,cpp]
--
double d {99.9};
int i =d;
--

Here an error would occur because we use list initialization which prevents narrowing conversions, but even then the compiler would still warn you regardless.

If you deliberately want the conversion:

`char ch {static_cast<char>(i) };` (where i is an integer and you are converting the integer to type char)

the cast communicates:

I intentionally want this conversion and accept the possibility of data loss. Which dosent magically make the conversion safe, just more explicit.

===== static_cast vs creating a temporary

You may sometimes see 
`int{x}` 
instead of:
`static_cast<int>(x)`

Both can produce temporary converted values, but they aren't completely interchangeable.

A major dfference is that list initialization rejects narrowing conversions.

== Typedefs and type aliases

=== Type aliases

A type alias creates an alternative name for an existing type. It does not create a new, distinct type. Rather, the alias and the original type are treated as the same type by C++.

Modern syntax uses using:

[source, cpp]
--
using Distance = double;

Distance miles {5.5};
--

Here distance is simply another name for double, so this is the same as creating a variable named miles of type double and storing the value 5.5 within it.

==== Why use type aliases?

Type aliases can make code easier to understand by giving a type a meaningful name.

Moreover, aliases can also make complicated types easier to write and read. For instance:

`using VectPairSI = std::vector<std::pair<std::string, int>>;`

Instead of repeatedly writing the entire underlying type, you can use VectPairSI.

==== Type aliases do NOT provide a type saftey

because an alias is only another name for an existing type:

[source,cpp]
--
using StudentId = int;
using EmployeeId = int;

StudentId student { 5 };
EmployeeId employee { student }; // valid
--

C++ ultimately sees both as int.

So aliases can provide semantic meaning to the programmer, but they do not prevenet accidently mxiing logically different values that share the same underlying type.

==== Typedef

typedef is the older way of creating type alises.

`typedef double Distance;`

is equivalent to 

`using Distance = double;`

The syntax is different, but the concept is the same. Using is better though, but recognize typedef in older C++/C code.

==== Naming type aliases

Type aliases are typically named starting with a capital letter, like other progammer defined types.

aliases ending with _t are also common.

However, learncpp reccomends avoiding defining your own _t names in the global name space, beacuse _t suffizes are commonly used by std/system defined types and may cause naming conflicts.

==== Type aliases and platform independent code

Aliases are useful when the exact underlying type may need to change. For example:

`using Int = int;`

Code can then use int through the program. if the underlying representation later needs ot change, you can potentially change the alias rather than every individual declaration.

However, aliases do not magically make code platform independent. The underlying type still has whatever properties and limitations the actual type has.

==== Type aliases and documentation

A type alias should have a clear purpsoe. If someone encounters 

`using TestScore = int;`

They can reasonably understand why the alias exists. Naming your alias Integer on the other hand, adds very little value that int didn't already communicate.

== Type deductions for using the auto keyword

=== Type deduction

Normally, when defining a variable you explicity give its type. However, with type deduction, C++ determines the variable's type from its initializer. It does this using the "auto" keyword

==== auto requires an initializer

Since the initializer is what C++ uses to determine the type, all variables initialized with type auto need a value otherwise auto has nothing to deduce the type from.

==== Type deduction uses the initializer's type

C++ deduces the type from thet ype of the initializer expression, not from what value would seem appropriate. What does this mean? Observe:

[source,cpp]
--
auto x { 5 };      // int
auto y { 5.0 };    // double
auto z { 5.0f };   // float
--

Basically you still need to understand C++
s literal types even when using auto.


==== auto and const

Type deduction normall drops top-level const.

This means that in the expressions

[source,cpp]
--
const int x {5};

auto y {x};
--

Here, y is just type int, not const int.

This amkes sense because y is a new independent object from x. The x is still of type const int, whereas the auto y is not. If you wanted the deducaed variable itself to be const, you'd have to explicitly state const auto y.

==== auto and string literals

auto does NOT deduce std::string since a tring literal is not inherently a std::string, so auto will deduce based on the string literal's actual type/decay behavior.

If you want a std::string, make that explicit.

Or if the appropriate string suffix is avaliable, then use that, so auto can deduce std::string.

==== why use auto?

. Avoiding redundant type names

Instead of calling a very obviously double, a double, you can write auto.

. Complicated types

Some C++ expressions produce types that are annoying or difficult to explicitly write.

auto lets the compiler handle that:

`auto result {someComplicatedExpreesion() };`

. Makes certain code easier to maintain

Let's say a function's return type changes. With an explicitly named variable:

`int result { getValue() };`

you may also need to update the variable.

With:

`auto result { getValue() };`

the variable automatically follows the function's return type

===== when auto can hurt readability

auto removes explicit type information from the declation.

for instance :

`auto x { 5 };`

this is clear since 5 is very much an int. But if I have, say

`auto value {getSomething()};`

This is not clear, especially if I am not the one who actually worte the code. This is when an explicit type is better than an auto.

==== auto does not mean the variable can change types

`auto x{5};`
After compilation, this is essentially the same as
`int x {5};`

x is now an int.

You cannot later make it a differnt type and assume auto will catch it. Instead, C++ would try to convert whatever type oyu assign x to in the future as an int.