= Control Flow

== Control flow introduction

When a program is ran, the CU begins execution at the top of main(), executes some number of statements, and then the program terminates at the end of main(). The specfici sequence of statements that the CPU executes is called the program's execution path (or path for short)

Consider the following program:

[source, cpp]
--
#include <iostream>

int main()
{
    std::cout << "Enter an integer: ";

    int x{};
    std::cin >> x;

    std::cout << "You entered " << x << '\n';

    return 0;
}
--

The execution path of this program includes lines 5, 7, 8, 10, and 12 in that order. This is an example of a straight line program.

Often this is not what we desire. For example, if we ask the user for input, and the user enters something invalid, ideally we would like to ask the user to make another chocie. This is not possible in a straight line program

C++ provides a number of different control flow statements, whicha re statements that allow the programmer to change the normal execution through the program. You've already seen an example of this with if statements.

=== Categories of flow control statements

There are:

* Conditional statements (if statements)
* Jumps (tells the CU to start executing statements elsewhere)
* Function calls (Jumps to some other location and back)
* Loops (repeatedely execute some sequnce of code zero or more times)
* Halts (Terminates the program)
* Exceptions (Designed for error handling)

=== If statements and blocks

The first control flow we will learn is a conditional

A conditional statement is a statement that specifies whether some associated statement(s) should be executed or not.

C++ supports two basic kinds of coniditonals: if statements and switch statements.

=== Implicit blocks

As you know, as a progammer you typically manually include the blocks for your conditionals. For instnace:

[source, cpp]
--
if(x>y){
    std::cout<< x " is bigger than " << y << '\n';
}
--

However, if you were to not include the blocks within your if statement, the compiler will implicitly declare one.

So that means:
[source, cpp]
--
if (condition)
    true_statement;
else
    false_statement;
--
would then turn into:
[source, cpp]
--
if (condition)
{
    true_statement;
}
else
{
    false_statement;
}
--

=== Null statements

A null statement is an expression statement that consists of just a semicolon

[source,cpp]
--
if (x>10)
    ;//this is a null statement
--
Null statements...do nothing. They are typically used when the language requires a statement to exist but the programmer dosen't need one.

== Constexpr if statements intro

Normally, the conditional of an if statement is ecaluated at runtime. However, consider the case where the conditional is a constant expression. In that case you can use the Constexpr to make the conditional evalute at compile time (before the program actually runs)

=== Constexpr if statements

The constexpr introduces the constexpr if statement, which requires the conditional to be a constant expression.

If the constexpr conditional evaluates to true, the entire if-else will be replaced by the true staement. if the constexpr conditional evalutes to false, the entire if-else will be replaced by the false-statement (if it exists) or nothing (if there is no else).

Here is an example:
[source,cpp]
--
#include <iostream>

int main()
{
	constexpr double gravity{ 9.8 };

	if constexpr (gravity == 9.8) // now using constexpr if
		std::cout << "Gravity is normal.\n";
	else
		std::cout << "We are not on Earth.\n";

	return 0;
}
--

== Switch statement basics

Although it is possible to chain many if-else statements together, it is both difficult to read and inefficient.

Because testing a variable or expression for equality against a set of different values is common, C++ provides an alternative conditional statement called a switch-statement that is specialized for this purpose. Here is a program using a swtich

[source, cpp]
--
#include <iostream>

void printDigitName(int x)
{
    switch (x)
    {
    case 1:
        std::cout << "One";
        return;
    case 2:
        std::cout << "Two";
        return;
    case 3:
        std::cout << "Three";
        return;
    default:
        std::cout << "Unknown";
        return;
    }
}

int main()
{
    printDigitName(2);
    std::cout << '\n';

    return 0;
}
--

The idea behind a switch statement is simple: an expression (sometimes called the condition) is evaluated to produce a value.

Then one of the following occurs:

* If the expression's value is equal to the value after any of the case-labels, the statements after the matching case-label are executed.

* If no matching value can be found and a default label exists, the statements after the default label are executed.

* If not matching values can be found and there is no default label, the switch is skipped.

=== Starting a switch

We start a switch statement by using the switch keyword, followed by parantheses with the conditional expression that we would like to evaluate.

The coniditon in a switch must evaluate to an integral type or an enumerated type. Expressions that evaluate to floating point types, strings, and most other non-integral types may not be used here.

=== Case labels

The first kind of label is the case label, which is declared using the case keyword and followed by a constant expression. The constant expression must either match the type of condition or must be convertible to that type.

Here is an example:
[source, cpp]
--
#include <iostream>

void printDigitName(int x)
{
    switch (x) // x is evaluated to produce value 2
    {
    case 1:
        std::cout << "One";
        return;
    case 2: // which matches the case statement here
        std::cout << "Two"; // so execution starts here
        return; // and then we return to the caller
    case 3:
        std::cout << "Three";
        return;
    default:
        std::cout << "Unknown";
        return;
    }
}

int main()
{
    printDigitName(2);
    std::cout << '\n';

    return 0;
}
--

Here the switch(x) is saying "Evaluate x", and then each case is saying, (if x evaluted to __, then execute the code below.)

As you can see, the program replaces x with 2, which then causes case 2 to execue since it is evaluted to 2, which causes 2 to print. Then we just print a newline too for visibility.

=== The default label

The default label or default case is just to have an "else" incase none of the cases match.

=== No matching case label and no default case

If you have no matching case label and no default case, then the entire switch is skipped and no statements are ran.

=== Taking a break

In the above examples, we used return statements to stop execution of the statements after our labels. This also exits the function [printDigitName(int x)]

A break statement(declared using the break keyword) tells the compiler that we are done executing statements within the switch, and that execution should continue with the statement after the end of the switch block. This alows us to exit a switch-statement without exiting the entire function.

here's a slightly modified example rewritten using break instead of return
[source, cpp]
--
#include <iostream>

void printDigitName(int x)
{
    switch (x) // x evaluates to 3
    {
    case 1:
        std::cout << "One";
        break;
    case 2:
        std::cout << "Two";
        break;
    case 3:
        std::cout << "Three"; // execution starts here
        break; // jump to the end of the switch block
    default:
        std::cout << "Unknown";
        break;
    }

    // execution continues here
    std::cout << " Ah-Ah-Ah!";
}

int main()
{
    printDigitName(3);
    std::cout << '\n';

    return 0;
}
--

Here, it runs the case 3, but then afterwords instead of exiting the function entirely, it still prints Ah-Ah-Ah since it never exited the function, only the switch.

== Switch fallthrough and scoping

=== Fallthrough

When a switch expression matches a case label or optional default label, execution begins at the first statement following the matching label. Execution will then continue ssequentially until one of the following termination conditions happens:

* The end of the switch block is reached
* Another control flow statement (typically a break or return) causes the switch block or function to exit
* Something else interrupts the normal flow of the program

Here is an example:
[source, cpp]
--
#include <iostream>

int main()
{
    switch (2)
    {
    case 1: // Does not match
        std::cout << 1 << '\n'; // Skipped
    case 2: // Match!
        std::cout << 2 << '\n'; // Execution begins here
    case 3:
        std::cout << 3 << '\n'; // This is also executed
    case 4:
        std::cout << 4 << '\n'; // This is also executed
    default:
        std::cout << 5 << '\n'; // This is also executed
    }

    return 0;
}
--

==== The [[fallthrough]] attribute

Commenting intentntional fallthrough is a common convention to tell other developers that fallthrough is intended. While this works for developers, the compiler and code analysis tool don't know how to interpret comments, so it won't get rid of the warnings

So you can add a [[fallthrough]] attribute for when you WANT fallthrough to occur, but don't want the compiler to raise an error.

Attributes are a modern C++ feature that allows the programmer to provide the compiler with some additional data about the code. To specify an attribute the attribute name is placed between double brackets. Attributes are not statements rather, they can be used almost anywhere if they are contextually reelevant.

=== Sequential case labels

You can use the logical OR operator to combine multiple tests into asingle statement

For example:

[source,cpp]
--
bool isVowel(char c)
{
    return (c=='a' || c=='e' || c=='i' || c=='o' || c=='u' ||
        c=='A' || c=='E' || c=='I' || c=='O' || c=='U');
}
--

This suffers from the same challenges we presented in the intrdouction to switch statements: c gets evaluated multiple times and the reader has to make sure it is c that is being evaluated each time.

If we did this instead with swtiches:
[source, cpp]
--
bool isVowel(char c)
{
    switch (c)
    {
    case 'a': // if c is 'a'
    case 'e': // or if c is 'e'
    case 'i': // or if c is 'i'
    case 'o': // or if c is 'o'
    case 'u': // or if c is 'u'
    case 'A': // or if c is 'A'
    case 'E': // or if c is 'E'
    case 'I': // or if c is 'I'
    case 'O': // or if c is 'O'
    case 'U': // or if c is 'U'
        return true;
    default:
        return false;
    }
}
--

Now if I type in a or e or i or even the uppercase varaints, it will immediately return true without having to check every single one.

=== Labels do not define a new scope

Each case that you have does not create a new block, everything within switch is defined to the switch block scope. So cases do not have their own scope.

=== Variable declaration and initialization inside case statements

You can declare or define (but not initialize) cariables inside the switch, both ebfore and after the case labels.

== Goto statements

The next kind of control flow statement we'll cover is the unconditional jump. An unconditional jump causes execution to jump to another spot in the code. The term "unconditional" means the jump always happens (unlike an if statement or switch statement, where the jump only happens conditionally.)

In C++ uncondtional jumps are impleneted via a goto statement, and the spot to jump to is identified through use of a statement label.

here is an example:
[source, cpp]
--
#include <iostream>
#include <cmath> // for sqrt() function

int main()
{
    double x{};
tryAgain: // this is a statement label
    std::cout << "Enter a non-negative number: ";
    std::cin >> x;

    if (x < 0.0)
        goto tryAgain; // this is the goto statement

    std::cout << "The square root of " << x << " is " << std::sqrt(x) << '\n';
    return 0;
}
--

In this program, we initialize a double variable, x, and then print "Enter a non-negative number". After that, we go and input the user's input inside of x. If the user enters an input that is below 0, we then go back to the tryAgain statement label which runs the process of inputting a non negative number again.

=== Statement labels have function scope

Statement labels do indeed have a function scope. There are two kinds of scope that we have covered, the block scope (or local scope), and the file (global scope). Well statements dont use either of this shit. Instead they use a third kind of scope: function scope, which means the label is visible throughout the funciton even before its point of declaration. The goto statement and its corresponding statement label must appear in the same function.

For example:
[source, cpp]
--
#include <iostream>

void printCats(bool skip)
{
    if (skip)
        goto end; // jump forward; statement label 'end' is visible here due to it having function scope

    std::cout << "cats\n";
end:
    ; // statement labels must be associated with a statement
}

int main()
{
    printCats(true);  // jumps over the print statement and doesn't print anything
    printCats(false); // prints "cats"

    return 0;
}
--

As you can see, here goto is jumping foward instead of back.

In the first case, we make skip as true, which then makes the printCats() function not print anything

However the printCats(false) instead says do not skip, which causes it to print cats.

There are two primary limitations to jumping:

* You can jump only within the bounds of a single function (you can't jump out of one function and into another), 

* if you jump foward, you can't jump foward over the initialization of any variable that is still in scope at the location you jumped to. 

For example:
[source, cpp]
--
int main()
{
    goto skip;   // error: this jump is illegal because...
    int x { 5 }; // this initialized variable is still in scope at statement label 'skip'
skip:
    x += 3;      // what would this even evaluate to if x wasn't initialized?
    return 0;
}
--

This jump is illegal because you are jumping OVER the initialization of x. 

=== Avoid using goto

Use of goto is shunned. The primary problem with goto is that it allows a programmer to jump around the code arbitrarily. This creates what is not-soaffectionately known as spaghetti code. Spaghetti code is code that has a path of execuion that is messy and unorganized.

== Introduction to loops and while statements

=== White statements

The while statement (also called a while loop) is the simplest of the three loop types that C++ provides, and it has a very similar definition to that of an if statement. here is the structure:

while (condition):
    statement

This is quite literally saying that while condition is true, the statement will occur.

For example:
[source, cpp]
--
#include <iostream>

int main()
{
    int count{ 1 };
    while (count <= 10)
    {
        std::cout << count << ' ';
        ++count;
    }

    std::cout << "done!\n";

    return 0;
}
--

=== While statements that evaluate to false initially

If the condiitonal initially evaluates to false, the associated statement will NEVER execute. 

=== infinite loops

If the expression always evalutes to true, the loop will execute forever, causing an infinite loop.

==== Intentional infinite loops

Sometimes you intentionally create an infinite loop and put a means of ending it through a user or a progammer side command. This is used for things like menus or other things you want to intentionally cause to loop.

==== Unintnetional infinite loops

On the contrary, you can have unintnentional infinite loops that break your program.

=== Loop variables and naming

A loop variable is a varibale that is used to control how many times a loop executes. Most loop variables have type int, you occasionally see other types such as char.

Loop variables are often given simple names, with i, j, and k being the most common.

==== Integral loop variables should be signed

If you have an integral loop variable, they should always be signed. as unsigned integers can lead to unexpected results.

=== Doing something every N iterations

If you are building a program that intentionally loops, maybe you want to do something after every N iterations. Such as after every X iterations, give the user a gold star or something. This can be done using the module operator, so instead of doing ( if count == 10 || count == 20), you can instead do if count % 10 == 0, which essentially says if the count is divisble by ten, which means every 10 times this thing loops, a statement will happen.

=== Nested loops

You can create nested loops which are loops inside of other loops. They are kinda confusing but they have their uses.

== Do while statements intro

Consider the case where we want to show the user a menu and ask them to make a selection -- and if the user chooses an invalid selection, to ask them again. Clearly the menu and selection should go inside of a loop of some kind (so we can keep asking the user until they wenter a valid input), but what kind of loop should we choose.

Since a while loop evaluates the condition up front, its an akward choice. We could solve the issue like this:

[source, cpp]
--
#include <iostream>

int main()
{
    // selection must be declared outside while-loop, so we can use it later
    int selection {}; // value initialized to 0

    while (selection < 1 || selection > 4)
    {
        std::cout << "Please make a selection: \n";
        std::cout << "1) Addition\n";
        std::cout << "2) Subtraction\n";
        std::cout << "3) Multiplication\n";
        std::cout << "4) Division\n";
        std::cin >> selection;
    }

    // do something with selection here
    // such as a switch statement

    std::cout << "You selected option #" << selection << '\n';

    return 0;
}
--

Here this program only works because our validity does not include 0 (because list initialization automatically does zero-initialization for integers when you leave the squiggly brackets empty)

So if we would want to include 0 as a valid choice, we'd have to pick a different initializer to represent invalid...which leads us to magic numbers.

=== Do while statements

A do while statement is a looping construct that works just like a while loop, except the statement always executes at least once. After the statement has been executed, the do-while loop checks the condition. If the coniditon evaluates to true, the path of execution jumps back to the top of the do while loop.

For example:
[source, cpp]
--
#include <iostream>

int main()
{
    // selection must be declared outside of the do-while-loop, so we can use it later
    int selection {};

    do
    {
        std::cout << "Please make a selection: \n";
        std::cout << "1) Addition\n";
        std::cout << "2) Subtraction\n";
        std::cout << "3) Multiplication\n";
        std::cout << "4) Division\n";
        std::cin >> selection;
    }
    while (selection < 1 || selection > 4);

    // do something with selection here
    // such as a switch statement

    std::cout << "You selected option #" << selection << '\n';

    return 0;
}
--

So basically, it DOES the things in the do section, and then while the condition in the while is true, it jumps back up to the do. 


== For statements

The for statement (or a for loop) is preferred when we have an obvious loop variable becasue it lets us easily and concisely define, initialize, test, and change the value of loop variables.

The for statement is pretty simple in concept:

for (init-statement; condition; end-expression)
    statement;

So here this is saying essentially,
[source, cpp]
--
type init-statement; //initialization of variables used in the for loop

while (condition) //condition using variables defined in the for loop
{
    statement;
    end-expression; // used to modify the loop variable prior to reassessment of the condition

}
--

=== Evaluation of for-statements

The for statement is evaluted in 3 parts:

* First the init-statement is executed. This only happens once, as the loop variables are reused for as long as the loop goes. These variables have "loop scope", which really just is a form of block scope where these variables exist from the point of definition through the end of the loop statement. 

* Second, with each loop iteration, the condition is evaluated. If the condition evalutes to true, the loop continues and the statement in it is executed. If false the loop terminates and execution continues with the next statement beyond the loop.

* Lastly, after the statement is executed, the end-expression is evaluted. Typically, this expression is used to increment a loop traker defined in the loop variables.
=== Off-by-one-errors

One of the biggest problems that new programmers have with for-loops are off-by-one errors.

Off-by-one errors occur when the loop iterates one too many or one too few times to produce the desired result. 

For example:
[source, cpp]
--
#include <iostream>

int main()
{
    // oops, we used operator< instead of operator<=
    for (int i{ 1 }; i < 5; ++i)
    {
        std::cout << i << ' ';
    }

    std::cout << '\n';

    return 0;
}
--

This program prints one less because we used the wrong operator.

=== Omitted expressions

It is possible to write for loops that omit any or all of the satements or expressions.

For instance:
[source, cpp]
--
#include <iostream>

int main()
{
    int i{ 0 };
    for ( ; i < 10; ) // no init-statement or end-expression
    {
        std::cout << i << ' ';
        ++i;
    }

    std::cout << '\n';

    return 0;
}
--

In this example, we do not have an initialization statement or end-expression.

Rather than having the for loop do the initialization and incrementinng, we have done it manually. Sometimes this is desired. Although you do not see it ver often.

=== For loops with multiple counters

Although for-loops typically iterate over only one variable, sometimes for loops need to work with multiple variables. To assist with this, the programmer can define multiple variables in the init-statement, and can make use of the comma operator to change the value of multiple variables in the end experssion.

=== Nested for-loops

For loops can be nested inside of other loops. 

For example:
[source, cpp]
--
#include <iostream>

int main()
{
	for (char c{ 'a' }; c <= 'e'; ++c) // outer loop on letters
	{
		std::cout << c; // print our letter first

		for (int i{ 0 }; i < 3; ++i) // inner loop on all numbers
			std::cout << i;

		std::cout << '\n';
	}

	return 0;
}
--

For each iteration of the outer loop, the inner loop runs its entirety. The resulting first output would be "a012" then "b012" then "c012" and so on.

=== Variables used only inside of a loop should be defined inside the loop

Look at this example:
[source, cpp]
--
#include <iostream>

int main()
{
    int i {}; // i defined outside loop
    for (i = 0; i < 10; ++i) // i assigned value
    {
        std::cout << i << ' ';
    }

    // i can still be accessed here

    std::cout << '\n';

    return 0;
}
--

Here i is still accessible even though the loop no longer needs it.

== Break and continue

Although you have already seen the break statement in the context of switch statements, it can also be used in loops too

The break statement causes a while loop, do while-loop, and for loop, or switch statement to end, with execution continuing with the next statement after the loop or switch being broken out of.


=== Breakking a switch

When you break a switch, the break prevents fall through and causes the next statement after the switch to run.

So for example:
[source, cpp]
--
#include <iostream>

void printMath(int x, int y, char ch)
{
    switch (ch)
    {
    case '+':
        std::cout << x << " + " << y << " = " << x + y << '\n';
        break; // don't fall-through to next case
    case '-':
        std::cout << x << " - " << y << " = " << x - y << '\n';
        break; // don't fall-through to next case
    case '*':
        std::cout << x << " * " << y << " = " << x * y << '\n';
        break; // don't fall-through to next case
    case '/':
        std::cout << x << " / " << y << " = " << x / y << '\n';
        break;
    }
}

int main()
{
    printMath(2, 3, '+');

    return 0;
}
--

Here after each break, the rest of the switch statement stops and the program exits the switch.

=== Breaking a loop

breaking a loop can be used to end the loop early. Execution continues with the next statement after the end of the loop

[source, cpp]
--
#include <iostream>

int main()
{
    int sum{ 0 };

    // Allow the user to enter up to 10 numbers
    for (int count{ 0 }; count < 10; ++count)
    {
        std::cout << "Enter a number to add, or 0 to exit: ";
        int num{};
        std::cin >> num;

        // exit loop if user enters 0
        if (num == 0)
            break; // exit the loop now

        // otherwise add number to our sum
        sum += num;
    }

    // execution will continue here after the break
    std::cout << "The sum of all the numbers you entered is: " << sum << '\n';

    return 0;
}
--

In this program, the loop exits if the user enters the number 0.

A break is also a common way to get out of an intentional infinite loop
[source, cpp]
--
#include <iostream>

int main()
{
    while (true) // infinite loop
    {
        std::cout << "Enter 0 to exit or any other integer to continue: ";
        int num{};
        std::cin >> num;

        // exit loop if user enters 0
        if (num == 0)
            break;
    }

    std::cout << "We're out!\n";

    return 0;
}
--

Here the break exits out of the infinite loop.

=== Break vs return

Break exits the loop and/or switch but still continues with the rest of the function. Break also dosent assign a specific value to the function itself.

Return both breaks out of the loop AND the function while also assigning whatever variable or literal you assigned as the value of the return to the function itself.

=== Continue

The continue statement provides a convenient way to end the current iteration of a loop without terminating the entire loop.

For example:
[source, cpp]
--
#include <iostream>

int main()
{
    for (int count{ 0 }; count < 10; ++count)
    {
        // if the number is divisible by 4, skip this iteration
        if ((count % 4) == 0)
            continue; // go to next iteration

        // If the number is not divisible by 4, keep going
        std::cout << count << '\n';

        // The continue statement jumps to here
    }

    return 0;
}
--

This loop has a count, per usual, and it also checks if the count is divisible by 4. Meaning every 4 times this loop occurs, it will go to the next iteration. Stopping the current iteration of the loop and starting the loop again from there.

== Halts (exiting your program early)

The last category of flow control statement is the halt

A halt is a flow control statement that terminates the program. In C++, halts are implemented as functionss (rather than kewywords), so our halt statements will be function calls.

=== The std::exit() function

the std::exit() function causes the program to terminal normally. Normal termination means the program has exited in an expected way.

==== Calling std::exxit() explicitly

Although std::exit() is called implicitly after function main returns, std::exit() can also be called explicitly to halt the program before it would normally terminate. When std::exit() is called this way, you need to include the cstdlib header.

==== std::exit() does not clean up local variables

std::exit() does not clean up any local variables. This means calling std::exit() can be dangerous if your program relies on any local variables cleaning themselves up.

=== std::atexit

Because std::exit() terminates the program immediately, you amy want to manually do some cleanup before terminating. 

In this context, cleaning means things like closing database or network connections, deallocating any memory you have allocated, writing information to a log file, etc.

You can use the cleanup function to manually cleanup before each std::exit, or you can use the std::atexit() function, which allows you to specify a function that will automatically be called on program termination via std::exit.

For example
[source, cpp]
--
#include <cstdlib> // for std::exit()
#include <iostream>

void cleanup()
{
    // code here to do any kind of cleanup required
    std::cout << "cleanup!\n";
}

int main()
{
    // register cleanup() to be called automatically when std::exit() is called
    std::atexit(cleanup); // note: we use cleanup rather than cleanup() since we're not making a function call to cleanup() right now

    std::cout << 1 << '\n';

    std::exit(0); // terminate and return status code 0 to operating system

    // The following statements never execute
    std::cout << 2 << '\n';

    return 0;
}
--

Here every time we exit, we will automatically call cleanup, rather than manually doing so.

=== std::abort and std::terminate

C++ contains two other halt-related functions

The std::about() function causes your program to terminate abnormally. Abnormal termination means the program had some kind of unusual runtime error and the program couldnt continue to run. For example, trying to divide by 0 will result in an abnormal termination.

std::terminate() function is typically used in conjuction with exceptions. It can be called explicitly, however, it is more often called implicitly when an exception isnt handled. By default, std::terminate() calls std::abort().

== Introduction to random number generation

=== Algorithms and state

First lets take about algorithms and states

Algorithms are often written using programming languages, allowing us to automate tasks. In C++ algorithms are typically implemented as reusable functions.

Here's a simple aglorithm for generating a sequence of numbers where each successive number is incremented by 1:

[source, cpp]
--
#include <iostream>

int plusOne()
{
    static int s_state { 3 }; // only initialized the first time this function is called

    // Generate the next number

    ++s_state;      // first we modify the state
    return s_state; // returns s_state to caller
}

int main()
{
    std::cout << plusOne() << '\n';
    std::cout << plusOne() << '\n';
    std::cout << plusOne() << '\n';

    return 0;
}
--

This algorithm is pretty simple. The s_state is declared static, which means it persists after the function ends, and the function itself increments s_state by one every time it is called. Afterwards it returns s_state as it currently is.

An algorithm is considered to be stateful if it retains some information across calls. conversely, a stateless algorithm does not store any information (and must be given all the information it needs to work whenever it is called). Our plusOne() function is stateful, in that it uses variable s_state to store the last number that was generated.

Our algorithm is consdiered determinisitc, meaning that for a given input (the value provided for start), it will always produce the same output sequence.

=== Psuedo-random number generators (PRNGs)

To simulate randomness, programs typically use a pseudo-random number generator. A pseudo-random number generator (PRNG) is an algorithm that generates a sequence of numbers whose properties simulate a sequnece of random numbers

Its easy to write a basic PRNG algorithm. Here's an example:

[source, cpp]
--
#include <iostream>

// For illustrative purposes only, don't use this
unsigned int LCG16() // our PRNG
{
    static unsigned int s_state{ 0 }; // only initialized the first time this function is called

    // Generate the next number

    // We modify the state using large constants and intentional overflow to make it hard
    // for someone to casually determine what the next number in the sequence will be.

    s_state = 8253729 * s_state + 2396403; // first we modify the state
    return s_state % 32768; // then we use the new state to generate the next number in the sequence
}

int main()
{
    // Print 100 random numbers
    for (int count{ 1 }; count <= 100; ++count)
    {
        std::cout << LCG16() << '\t';

        // If we've printed 10 numbers, start a new row
        if (count % 10 == 0)
            std::cout << '\n';
    }

    return 0;
}
--

==== Seeding a PRNG

The sequence of random numbers generated by a PRNG is not random at all. Just like our plusOne() function, LCG16() is also determinisitc. Give some initial state value (such as 0), a PRNG will generate the same sequence of numbers each time. If you run the above program 3 times, you'll see it generates the same sequence of values each time.

In order to generate different output sequences, the initial state of a PRNG needs to be varied. The value (or set of values) used to set the initial state of a PRNG is called a random seed (or seed for short). When the initial state of a PRNG has been set using a seed, we say it hass been seeded.

===== Seed quality and underseeding

If we want the program to produce different randomized numbers each time it is run, then we need some way to vary the seed each time the program is run. Asking the user to provide a seed value isn't great, since they can just add the same one twice. The program needs some way to generate a randomized seed value each time it is run. We can't use PRNG to generate a randomized seed, because we need a randomized seed to generate random numbers.

Insead, we'll typically use a seed generation algorithm that is designed to produce seed values.

The theoretical maximum number of unique sequences that a PRNG can generate is determined by the number of bits in the PRNG's state. For example, a PRNG with 128 bits of state can theoretically generate up to 2^128 unique output sequences

However, which output sequence is actually generated depends on the initial state of the PRNG, which is determined by the seed. Therefore, practiacally speaking, the number of unique output sequences a PRNG can actually generate is limited by the number of unique seed values the program using the PRNG can provide. 

If a PRNG is not provided with enough bits of quality seed data, we say that it is underseeded.

==== There are a lot of different PRNG algorithms

PRNG algorithms arent "one" thing. There are a LOT, with pros and cons across the board.

=== Randomization in C++

the randomization capabilities in C++ are accessible via the <random> header of the standard library. Within the radnom library, there are 6 PRNG families available for use.

* minstd_rand, minstd_rand0 (bad)
* mt19937, mt19937_64 (Decent)
* ranlux24, ranlux48 (AWFUL)
* knuth_b (awful)
* rand (bad)

== Generating random numbers using Mersenne Twister

Generating random numbers in C++ using Mersenne Twister

The Mersenne Twister PRNG, besides having a great name, is probably the most popular PRNG acorss all programming languages. Although, it is  abit old by today's standards. It generally produces quality results and has decent performance.

The random library has support for two Mersenne Twister types:

* my19937 (generates 32 bit unsigned integers)
* mt19937_64 (generates 64-bit unsigned integers)

Using it is easy:

[source, cpp]
--
#include <iostream>
#include <random> // for std::mt19937

int main()
{
	std::mt19937 mt{}; // Instantiate a 32-bit Mersenne Twister

	// Print a bunch of random numbers
	for (int count{ 1 }; count <= 40; ++count)
	{
		std::cout << mt() << '\t'; // generate a random number

		// If we've printed 5 numbers, start a new row
		if (count % 5 == 0)
			std::cout << '\n';
	}

	return 0;
}
--

=== Limiting range

PRNGs cant naturally limit the range of the numbers. Meaning the numbers will always be randomly chosen with the full range in mind.

Fortunately, the random library can help here in the form of random number distributions. A random number distribution converts the output of a PRNG into some other distribution of numbers.

The random library has many random numbers distributions, most of which you will never use unless you're doing some kinda of statistical analysis. but there's one random number distribution that's extremely useful: a unfiform distrbution is a random number distribution that produces outputs between two numbers X and Y (inclusive) with equal probability.

Here's an example:
[source, cpp]
--
#include <iostream>
#include <random> // for std::mt19937 and std::uniform_int_distribution

int main()
{
	std::mt19937 mt{};

	// Create a reusable random number generator that generates uniform numbers between 1 and 6
	std::uniform_int_distribution die6{ 1, 6 }; // for C++14, use std::uniform_int_distribution<> die6{ 1, 6 };

	// Print a bunch of random numbers
	for (int count{ 1 }; count <= 40; ++count)
	{
		std::cout << die6(mt) << '\t'; // generate a roll of the die here

		// If we've printed 10 numbers, start a new row
		if (count % 10 == 0)
			std::cout << '\n';
	}

	return 0;
}
--

HOWEVER, even though each number produces by this algorithm will be random after the next one, the number sequence itself will NOT be. Meaning the same numbers will be produced in the same sequence every single time.

In order to make our entire sequence randomized differently each time the program is run. To do that, we just need to pick something that changes each time the program is run. Then we can use our PRNG to generate a unique sequence of pseudo-random numbers from that seed.

There are two methods that are commonly used to do this:

* Use the system clock
* Use the system's random device

==== Seeding with a system clock

The one thing that will always be different when you run your program? The TIME. Yup. Therefore, we use the current time as our seed value, then our program will produce a different set of random numbers each time it is run. C and C++ have a long history of PRNGS being seeded using hte current time (using the std::time() function).

C++ has a chrono library containing various clocks that we can use to generate a seed value.

To minimize the chance of two time values being identical if the program is run quickly in succession, we want to use some time measure that changes as quickly as possible. for this, we'll ask the clock how much time has passed since the earliest time it can measure. This time is measured in "ticks", which is a very small unit of time (usually nanoseconds, but could be milliseconds).

[source, cpp]
--
#include <iostream>
#include <random> // for std::mt19937
#include <chrono> // for std::chrono

int main()
{
	// Seed our Mersenne Twister using steady_clock
	std::mt19937 mt{ static_cast<std::mt19937::result_type>(
		std::chrono::steady_clock::now().time_since_epoch().count()
		) };

	// Create a reusable random number generator that generates uniform numbers between 1 and 6
	std::uniform_int_distribution die6{ 1, 6 }; // for C++14, use std::uniform_int_distribution<> die6{ 1, 6 };

	// Print a bunch of random numbers
	for (int count{ 1 }; count <= 40; ++count)
	{
		std::cout << die6(mt) << '\t'; // generate a roll of the die here

		// If we've printed 10 numbers, start a new row
		if (count % 10 == 0)
			std::cout << '\n';
	}

	return 0;
}
--

==== Seeding with the random device

The random library contains a type called std::random_device that is an implentation defined PRNG. normally we avoid implentation defined capabilities because they have no guarantees about quality or portability, but this is one of the exception cases.

Typically std::random_device will ask the OS for a pseudo-random number

[source, cpp]
--
#include <iostream>
#include <random> // for std::mt19937 and std::random_device

int main()
{
	std::mt19937 mt{ std::random_device{}() };

	// Create a reusable random number generator that generates uniform numbers between 1 and 6
	std::uniform_int_distribution die6{ 1, 6 }; // for C++14, use std::uniform_int_distribution<> die6{ 1, 6 };

	// Print a bunch of random numbers
	for (int count{ 1 }; count <= 40; ++count)
	{
		std::cout << die6(mt) << '\t'; // generate a roll of the die here

		// If we've printed 10 numbers, start a new row
		if (count % 10 == 0)
			std::cout << '\n';
	}

	return 0;
}
--

* Note, ONLY seed a PRNG once. You can reseed them after the initial seeding, but it should usually be avoided unless you have a specific reason.

=== Mersenne Twister and underseeding issues

The internal state of a Mersenne Twister requires 19937 bits (2493 bytes), which is 624 32 bit values or 312 64 bit values. As a result, std::mt19937 allocates 624 integers, whereas std::mt19937_64 allocates 312 integers.

In the examples above, where we seed our std::mt19937 from the clock or std::random device, our seed is only a single integer. This means we're esentially initializing 624 integers using a single integer, which is underseeding Mersenne twister PRNG.

There are some suggestions as to possible solutions

==== std::seed_seq

std::seed_seq is a type that was designed to help with this. We can pass it as many randomized values as we have, and then it will generate as many additional unbiased seed values as needed to intiialize a PRNG's state. 

If you intiailized std::seed_seq with a single value (e.g. from std::random_device) then initialize a Mersenne Twister with the std::seed_seq object, std::seed_seq will generate 623 values of additional seed data. This won't add randomness, but it will give us a better mix of 0 and 1 bits. However, the more data we can provide std::seed_seq, the better job it will do for us. So the easiest idea is to simply use std::random_device to give std::seed_seq more data to work with. If we initialize std::seed_seq with 8 values from std::random_device instead of 1, then the reamining values generated by std::seed_seq should be much better:
[source, cpp]
--
#include <iostream>
#include <random>

int main()
{
	std::random_device rd{};
	std::seed_seq ss{ rd(), rd(), rd(), rd(), rd(), rd(), rd(), rd() }; // get 8 integers of random numbers from std::random_device for our seed
	std::mt19937 mt{ ss }; // initialize our Mersenne Twister with the std::seed_seq

	// Create a reusable random number generator that generates uniform numbers between 1 and 6
	std::uniform_int_distribution die6{ 1, 6 }; // for C++14, use std::uniform_int_distribution<> die6{ 1, 6 };

	// Print a bunch of random numbers
	for (int count{ 1 }; count <= 40; ++count)
	{
		std::cout << die6(mt) << '\t'; // generate a roll of the die here

		// If we've printed 10 numbers, start a new row
		if (count % 10 == 0)
			std::cout << '\n';
	}

	return 0;
}
--

== Global random numbers (Random.h)

What happens if we want to use a random number generator in multiple functions or files? One way is to create (and seed) our PRNG in our main() function, and then pass it everywhere we need it. But thats a shit ton of work!

So instead, you could create a static local std::mt19937 variable in each function that needs it. However, its overkill to have every function that uses a random number generator define and seed its own local generator.

What we really want is a single PRNG object that we can share access anywhere, across all of our function and files. The best option here is to createa  global random number generator object (inside a namespace).

Here is a header only solution that you can #include in any code file that needs access to a randomized, self-seeded std::mt19937

Random.h
[source, cpp]
--
#ifndef RANDOM_MT_H
#define RANDOM_MT_H

#include <chrono>
#include <random>

// This header-only Random namespace implements a self-seeding Mersenne Twister.
// Requires C++17 or newer.
// It can be #included into as many code files as needed (The inline keyword avoids ODR violations)
// Freely redistributable, courtesy of learncpp.com (https://www.learncpp.com/cpp-tutorial/global-random-numbers-random-h/)
namespace Random
{
	// Returns a seeded Mersenne Twister
	// Note: we'd prefer to return a std::seed_seq (to initialize a std::mt19937), but std::seed can't be copied, so it can't be returned by value.
	// Instead, we'll create a std::mt19937, seed it, and then return the std::mt19937 (which can be copied).
	inline std::mt19937 generate()
	{
		std::random_device rd{};

		// Create seed_seq with clock and 7 random numbers from std::random_device
		std::seed_seq ss{
			static_cast<std::seed_seq::result_type>(std::chrono::steady_clock::now().time_since_epoch().count()),
				rd(), rd(), rd(), rd(), rd(), rd(), rd() };

		return std::mt19937{ ss };
	}

	// Here's our global std::mt19937 object.
	// The inline keyword means we only have one global instance for our whole program.
	inline std::mt19937 mt{ generate() }; // generates a seeded std::mt19937 and copies it into our global object

	// Generate a random int between [min, max] (inclusive)
        // * also handles cases where the two arguments have different types but can be converted to int
	inline int get(int min, int max)
	{
		return std::uniform_int_distribution{min, max}(mt);
	}

	// The following function templates can be used to generate random numbers in other cases

	// See https://www.learncpp.com/cpp-tutorial/function-template-instantiation/
	// You can ignore these if you don't understand them

	// Generate a random value between [min, max] (inclusive)
	// * min and max must have the same type
	// * return value has same type as min and max
	// * Supported types:
	// *    short, int, long, long long
	// *    unsigned short, unsigned int, unsigned long, or unsigned long long
	// Sample call: Random::get(1L, 6L);             // returns long
	// Sample call: Random::get(1u, 6u);             // returns unsigned int
	template <typename T>
	T get(T min, T max)
	{
		return std::uniform_int_distribution<T>{min, max}(mt);
	}

	// Generate a random value between [min, max] (inclusive)
	// * min and max can have different types
        // * return type must be explicitly specified as a template argument
	// * min and max will be converted to the return type
	// Sample call: Random::get<std::size_t>(0, 6);  // returns std::size_t
	// Sample call: Random::get<std::size_t>(0, 6u); // returns std::size_t
	// Sample call: Random::get<std::int>(0, 6u);    // returns int
	template <typename R, typename S, typename T>
	R get(S min, T max)
	{
		return get<R>(static_cast<R>(min), static_cast<R>(max));
	}
}

#endif
--

==
