"""Added more data to users (about me and last_seen)

Revision ID: 284ee27eb757
Revises: cb159f75073b
Create Date: 2026-07-27 20:44:49.793435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284ee27eb757'
down_revision = 'cb159f75073b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
