= Fundamental Data Types

== Void

=== Void and Incomplete types

Void means having "no type".

It is our first example of an incomplete type.

An incomplete type is a type that has been declared but not yet defined. The compiller knows about the existence of such types, but does not have enough information to determine how much memory to allocate for objects of that type.

Void is intentionally incomplete since it represents the lack of a type, and thus, cannot be efined.

Void is typically used in several different contexts

=== Functions that do not return a value

Void is commonly used to indicate that a function does not return a value. For example:

[status, cpp]
--
void print_name(name)
{
    std::cout << name << '\n';
}
--

=== Functions that do not take parameters (Depracted)

In C, void is used as a way to indicate that function does not take any parameters:

[status, cpp]
--
int getValue(void) //void here means no parameters
{
    int x {};
    std::cin >> x
    
    return x;
}
--

This use of void is considered deprecated in C__. It is preferred you just don't use void as a parameter at all.

== Object sizes and the sizeof operator

=== Memory

Just to clarify, most objects actually take up more than 1 byte of memory. A single object may use 1, 2, 4, 8, or even more consecutive memory addresses. The amount of memory than an object uses is based on its data type.

The compiler is able to hide the details of how many bytes a given object uses from us since we access objects through variable names and not directly via memory addressess. 

Even so, there are several reasons it is useful to know how much memory an object uses

First, the more memory an object uses, the more information it can hold.

A single bit can hold 2 possible values, a 0, or a 1:

[cols="1", options="header"]
|===
|bit 0

| 0
| 1
|===

2 bits can hold 4 possible values:
[cols="1,1"]
|===
|bit 0 |bit 1

|0
|0

|0
|1

|1
|0

|1
|1
|===


3 bits can hold 8 possible values:
[cols "1,1,1" options='header']
|===
|bit 0 |bit 1 | bit 2

|0
|0
|0

|0
|0
|1

|0
|1
|0

|0
|1
|1

|1
|0
|0

|1
|0
|1

|1
|1
|0

|1
|1
|1
|===

To generalize, an object with n bits(where n is an integer) can hold 2^n. Therefore with an 8 bit byte, a byte sized object can hold 2^8(256) different values. An object that uses 2 bytes therefore can hold 2^16(65536) different values.

Thus, the size of the object puts a limit on the amount of unique values it can sotre.

Second, computers have a finite amount of free memory. Every time we define an object, a small portion of that free memory is used for as long as the object is in existence. Because modern computers have a lot of memory, this impact is usually negligible.

=== Fundamental data type sizes

* An object must occupy at least 1 byte
* a byte must be at least 8 bits
* the intergral types char, short, int, long, and long long have a min size of 8, 16, 16, 32, and 64 bits respectively
* char and char8_t are exactly 1 byte (at least 8 bits)

==== Overview
Just as an overview recall for most modern architectures

* A byte is 8 bits
* Memory is byte addressable (we can access every byte of memory independently)
* Floating point support is IEEE-754 compliant
* We are on a 32-bit or 64-bit architecture


[cols "2,2,2,2"]
|===
| Category | Type |Minimum Size | Typical Size

|Boolean 
|bool
|1 byte
|1 byte

|Character
|char
|1 byte(exactly)
|1 byte

|
|wchar_t
|1 byte
|1 byte

|
|char8_t
|1 byte
|1 byte

|
|char16_t
|2 bytes
|2 bytes

|
|char32_t
|4 bytes
|4 bytes

|Integral
|short
|2 bytes
|4 bytes

|
|int
|2 bytes
|4 bytes

|
|long
|4 bytes
|4 or 8 bytes

|
|long long
|8 bytes
|8 bytes

|Floating point
|float
|4 bytes
|4 bytes

|
|double
|8 bytes
|8 bytes

|
|long double
|8 bytes
|8, 12, or 16 bytes

|Pointer
|std::nullptr_t
|4 bytes
|4 or 8 bytes
|===

