= Constants and Strings

== Constant variables(named constants)

=== Constants

A constant is a value that may noy be changed during the program's execution.

There are two different types of constants:

* Named constants: constant values that are associated with an identifier. These are also sometimes called symbolic constants.

* Literal constants: constant values that are not associated with an identifier.

=== Types of named constants

There are three ways to define a named constant in C++

* Constant variables
* Object-like macros with substitution text
* Enumerated constants

=== Constant variables

So far, all of the variables we've seen have been non-constant, that is, their values can be cahnges at any time.

However, there are many cases where it is useful to define varibales with values that cannot be changed. For example, the gravity of the earth near the earth's surface. That isn't likely to change any time soon.

=== Declaring a const variable

To declare a constant variable, we place the const keyword (called a const qualifer) adjacent to the object's type.

For example:
`const double gravity {9.8};`

* Note: Constant variables MUST be intialized when you define them.

=== Const function parameters

Function parameters can be made constants via the const keyword.

Making a function parameter constant enlists the compilers help to ensure that the parameter's value is not changed inside the function. (However, this isn't really done in modern C++)

=== Why variables should be made constant

If a variable can be made constant, it generally should be made constant:

* It reduces the chance of bugs. (You can't accidently change a variable)

* It provides opprotunity for the compiler to optoize programs. 

* It reduces the overall complexity of programs


=== Object-like macros with substitution text

For reference, here is an object-like macro with substitution text:

[source, cpp]
--
#include <iostream>

#define MY_NAME "Alex"

// Now whenever we use identifier MY_NAME it'll give the value "Alex"

int main()
{
    std::cout << "My name is " << MY_NAME << '\n';

    return 0;
}
--

Object-like macros with sub text are also named constants, since they aren't changing anytime soon.

=== Prefer constant variables to preprocessor macros

So why not use preprocessor macros for named constants? There are three major problems to this.

* Macros don't follow normal C++ scoping rules (Once a macro is defined, all subsequent occurrences of the amcro's name in the current file will be replaced. If that name is used elsewhere, you'll get macro substitutions where you don't want it.)

* It is often harder to debug code using macros

* Macro subs behave differently than everything else in C++ so why make shit harder for urself bro.

== Literals

=== The type of a literal

Just like objects have a type, all literals have a type. The type of a literal is deduced from the literal's value. Like a whole number literal such as 5 is an integer...because it gives the integer value of 5!

You can probably guess all other literals using this logic. (true or false iss a bool, 'A' is a char etc.)

=== Literal suffixes

If the default type of a literal is not as desired, you can change the type of a ltieral by adding a suffix. (we did this before by making some literals floats by adding f at the end of them.)

==== Suffix casing

Most suffixes are not case sensitive, but also some are.

s and sv must be lowercase, and two consecutive l or L characters must have the same casing (so either ll or LL)

=== Integral literals

You generally won't need suffizes for integral literals, but an example would be:

`std::cout << 5L;`
This 5L is type long.

=== Floating point literals

By default, floating point literals have a type of double. To make them float literals instead, the f or F suffix should be used.

* Note: for scientific notaiton, use e to represent the exponent

=== String literals

A string is a collection of sequential characters used to represent text (e.g. "Hello world!")

* All C-style literals have an implicit null terminator. This means every string is a group of characters (e.g. hello is 'h' 'e' 'l' 'l' 'o') and also a '\0' character. This trailing '\0' character is called a null terminator, and it is used to indicate the end of the string. A string that ends witha  null terminator is called a null-terminated string.


=== Magic numbers

A magic numer is a literal that either has unclear meaning or may need to change later.

For example:
[source, cpp]
--
const int maxStudentsPerSchool{ numClassrooms * 30}
setMax(30);
--

What do the literals 30 mean in these contexts? In the former, you can probably guess that it's the number of students per class. But in the latter, who knows!

In complex programs, it can be very difficult to infer what a literal represents unless there's a comment to explain it.

Using magic numbers is generally considered to bad practice because, in addition to not providing conext as to what they are being used for, they pose problems if the value needs to change. Let's assume the school buys new desks that allow them to reise the class size from 30 to 35. 

In order to reflect that, we need to update one or more ltieral from 30 to 35. But which literals/ the 30 initializer of maxStudentsPerSchool seems obvious. But what about the 30 used an argument to setMax()? Does that 30 have the same emaning as the other 30? If so, it should eb updated. If not, it should be left alone, or we might break our program somehwere else.

If you do a global search-and-replace, you might inadvertently update the argument of setMax() when it wasn't supposed to change. 

Both lack the context and issues around updating and can easily be addressed by using symbolic constants

[source, cpp]
--
const int maxStudentsPerClass { 30 };
const int totalStudents{ numClassrooms * maxStudentsPerClass }; // now obvious what this 30 means

const int maxNameLength{ 30 };
setMax(maxNameLength); // now obvious this 30 is used in a different context
--

== Numeral systems (decimal, binary, hexadecimal, and octal)

=== Decimal and Binary

In binary there are only 2 digits, 0 and 1, so it is called base 2. In binary we count like this 0, 1, 10, 11, 11001, to make them easier to read, longer binary numbers are often space-separated into groups of 4 digits.

Decimal and binary are two examples of numeral systems, which is a fancy name for a collection of symbols that are used to represent numebrs.

=== Octal and hexadecimal literals

Octal is base 8, that is there are only 8 digits available (0-7). in octal you can count like this:

1,2,3,4,5,6,7,10,11,12...

There is no 8 or 9 so you skip to 10.

To use an octal literal, prefix your literal with a 0(zero):

`int x{ 012 };`

Hexadecimal is base 16, and you count like this:

0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F,10,11,12...

You can also use lower case letters. To use a hexadecimal literal, prefix your literal with 0x:

`int x {0xF}`

=== Using hexadecimal to represent binary

Because there are 16 different values for a hexadecimal digit, we can say that a single hexadecimal digit encompasses 4 bits. 

Consequently, a pair of hexadecimal digits can be used to exactly represent a full byte.

=== Binary literals

You can use binary literals using the 0b prefix:

[source, cpp]
--
#include <iostream>

int main()
{
    int bin{};        // assume 16-bit ints
    bin = 0b1;        // assign binary 0000 0000 0000 0001 to the variable
    bin = 0b11;       // assign binary 0000 0000 0000 0011 to the variable
    bin = 0b1010;     // assign binary 0000 0000 0000 1010 to the variable
    bin = 0b11110000; // assign binary 0000 0000 1111 0000 to the variable

    return 0;
}
--

For long literals, you can also use a quotation mark as a digit separator

=== Outputting values in decimal, octal, or hexadecimal

C++ outputes are usualyl in decimal. However, you can change the output format via the use of std::dec, std::oct, and std::hex I/O manipulators.

=== Outputting values in binary

std::bitset will do this for is (in the <bitset> header)

To use std::bitset, we can define a std::bitset variable and tell std::bitset how many bits we want to store. The number of bits must be a compile time constant. std::bitset can be initialized with an integral value (in any format).

example:
[source, cpp]
--
#include <bitset> // for std::bitset
#include <iostream>

int main()
{
	// std::bitset<8> means we want to store 8 bits
	std::bitset<8> bin1{ 0b1100'0101 }; // binary literal for binary 1100 0101
	std::bitset<8> bin2{ 0xC5 }; // hexadecimal literal for binary 1100 0101

	std::cout << bin1 << '\n' << bin2 << '\n';
	std::cout << std::bitset<4>{ 0b1010 } << '\n'; // create a temporary std::bitset and print it

	return 0;
}
--

=== The as-if rule and compile-time optomization

=== Optomization

Optomizaiton is when you change different parts of your code to make it more efficient. Some things can help you with this:

* Profiler: A program that can be used to see how long various parts of the program are taking to run, and which are impacting overall performance.

* Optimizer: Typically work at low-level, looking for ways to imporve statments or expressions by rewriting, integral values, all of these produce the same result but one might be slightly faster than the other.

=== The as-if rule

In c++ compilers are given a lot of leeway to optomize programs. The as-if rule says that the compile can modify a program hwoever it likes to produce more optomized code, so long as thsoe modifications do not affect a program's "obervable behavior"

=== Constant folding

One of the original forms of compile-time evaluation is called "constant-folding".

Constnat folding is an optomization technique where the compiler replaces expressions that have litearl operands  with the result of the expression. Using constant folding, the compiler would recognize that the expression 3 + 4 has constant operands, and then replace the expression with the result 7.


=== Constant propogation

Let's look at this program.
[source, cpp]
--
#include <iostream>

int main()
{
	int x { 7 };
	std::cout << x << '\n';

	return 0;
}
--

When x is initialized the value 7 will be stored in the memory allocated for x. Then on the next line, the program will go out to memory again to fetch the value 7 so it can be printed. This requires two memory access operations

Constant propogation is a technique where the compiler replaces variables known to have constnat values with their values. Using constnat propogation, the compiler would realize x always has the contant value 7, and replace any use of variable x with the value 7.

* Note: Costant variables are easier to optomizer because of this

=== Dead code elimation

Dead code elimination is an optomization technique where the compiler removes code that may be executed but has no effect on the program's behavior.


=== Optomization can make programs harder to debug

When the compiler optomizes a program, the result is a variety of variables, expressions, that may have been rearranged, modified, replaced, or removed entirely, which makes debugging more difficult.

== Constant expressions

=== The benefits of compile-time programming

While the as-if rule is great for improving performance, it elaves us relaiant on the sophistication of the compiler to actually determine what can evaluate at compile-time, or witha  different compiler, or using different compilation options, or slightly modified, may produce a different result.

To improve this situation, the C++ language provides ways for us to be explicit about what parts of code we want to execute at compile-time. The use of language features that result in compile-time evaluation is called compile-time programming.

These features can:

* Aid in performance; compile-time evaluation amkes our programs smaller and faster

* Aid in versaltility; we can always use such code in placed that require a compile-time value

* Aid in predictability

* Aid in quality

* Aid in preventing undefined behavior during compile-time.

== Constexpr variables

=== The compile-time const challenge

A constant expression is typically created using the const keyword. A const variable with an integral type and a constant expression initializer can be used in a constant expression.  All other const variables cannot be used in constant expressions.

However, the use of const to create variables that can be used in constant expressions has a few challenges.

First, the use of const does not make it immediately clear whether the variable is useable in a constant expression or not. In some cases, we can figure it out fairly easily:

[source, cpp]
--
int a { 5 };       // not const at all
const int b { a }; // clearly not a constant expression (since initializer is non-const)
const int c { 5 }; // clearly a constant expression (since initializer is a constant expression)
--

=== The contexpr keyword

We can enlist the compiler's help to ensure we got a compile-time constant.

To do so, we use the constexpr keyword instead of const in a variable's declaration. A constexpr variable is always a compile-time constant. 

As a result, a constexpr variable must be initialized with a constant expression, otherwise a compilation error will result.
[source, cpp]
--
#include <iostream>

// The return value of a non-constexpr function is not constexpr
int five()
{
    return 5;
}

int main()
{
    constexpr double gravity { 9.8 }; // ok: 9.8 is a constant expression
    constexpr int sum { 4 + 5 };      // ok: 4 + 5 is a constant expression
    constexpr int something { sum };  // ok: sum is a constant expression

    std::cout << "Enter your age: ";
    int age{};
    std::cin >> age;

    constexpr int myAge { age };      // compile error: age is not a constant expression
    constexpr int f { five() };       // compile error: return value of five() is not constexpr

    return 0;
}
--

==== Overview

Const means the value cannot be changed AFTER intitialization.

contexpr means that the value can be used in a constant expression.

=== Constexpr functions

A constexpr function is a function that can be called in a constant expression. So that means it must evaluate at coimpile-time when the constant expression it is part of must evaluate at compile time, otherwise, a constexpr function may be evaluated at either compile time or runtime. 

To make a constexpr function, the constexpr keyword is placed in the function declaration before the return type:

[source, cpp]
--
#include <iostream>

int max(int x, int y) // this is a non-constexpr function
{
    if (x > y)
        return x;
    else
        return y;
}

constexpr int cmax(int x, int y) // this is a constexpr function
{
    if (x > y)
        return x;
    else
        return y;
}

int main()
{
    int m1 { max(5, 6) };            // ok
    const int m2 { max(5, 6) };      // ok
    constexpr int m3 { max(5, 6) };  // compile error: max(5, 6) not a constant expression

    int m4 { cmax(5, 6) };           // ok: may evaluate at compile-time or runtime
    const int m5 { cmax(5, 6) };     // ok: may evaluate at compile-time or runtime
    constexpr int m6 { cmax(5, 6) }; // okay: must evaluate at compile-time

    return 0;
}
--

== Introduction to std::string

=== std::string

std::string is a type that lives in the <string> header

We can create objects of type std::string just like other objects.

=== String output with std::cout

std::string objects cna be outputed as expected with std::cout

=== std::string can handle strings of different lengths

std::string can store strings of different lengths

=== std::string input with std::cin

cin breaks up on whitespace, so when you are inputting values intro a string, recall that spaces break up whatever value you input into cin.


==== Use std::getline() to input text

There is a solution to this. You can use std::getline() function instead, which requires two arguments. The first is std::cin and the second is your string variable.


So if you wanted to get someone's full name it would look like:

`std::getline(std::cin >> std::ws, name)`

===== What the fuck is std::ws??

Okay sooo we discussed output manipulators right? Which allow us to alter the way output is displayed. We used the ouptut manipulator function, std::setprecision() to change the number of digits of precision that std::cout displayed for instnace.

C++ also supports INPUT manipulators. Pretty cool huh? Which alter the way that input is accepted. The std::ws input manipulator tells std::cin to ignore any leading white space before extraction. Leading white space is any whitepsace character(spaces, tabs, newlines) that occur at the START of the string. Why is this useful? observe.

[source, cpp]
--
#include <iostream>
#include <string>

int main()
{
    std::cout << "Pick 1 or 2: ";
    int choice{};
    std::cin >> choice;

    std::cout << "Now enter your name: ";
    std::string name{};
    std::getline(std::cin, name); // note: no std::ws here

    std::cout << "Hello, " << name << ", you picked " << choice << '\n';

    return 0;
}
--

Here's some output from this program:

Pick 1 or 2: 2
Now enter your name: Hello, , you picked 2

This program first asks you to enter 1 or 2, and waits for you to do so. All good so far. Then it will ask you to enter your name. However, it won't actually wait for you to enter your na,e! Instead, it prints the hello string then exits.

When you enter a value using operator >>, std::cin not only captures the value, it also captures the newline character ('\n') that occurs when you hit the enter key. So when we type 2 and then hit enter, std::cin captures the string "2\n". 

Then, when std::getline() goes to extract text to name, it sees "\n" is already waiting in std::cin, and figures we must have previously entered an empty string!

We can ammend the program to use the std::ws input manipulator, to tell std::getlin() to ignore any leading whitespace characters.

[source, cpp]
--
#include <iostream>
#include <string>

int main()
{
    std::cout << "Pick 1 or 2: ";
    int choice{};
    std::cin >> choice;

    std::cout << "Now enter your name: ";
    std::string name{};
    std::getline(std::cin >> std::ws, name); // note: added std::ws here

    std::cout << "Hello, " << name << ", you picked " << choice << '\n';

    return 0;
}
--

=== Length

You can ask a std::string for its length via .length(),

so if you have name as a std::string object, you can do name.length() to get its length.

=== Literals for std::string
You can create string literals with the type std::string by using a s suffix after the double-quoted string literal.

For intance:
[source, cpp]
--
#include <iostream>
#include <string> // for std::string

int main()
{
    using namespace std::string_literals; // easy access to the s suffix

    std::cout << "foo\n";   // no suffix is a C-style string literal
    std::cout << "goo\n"s;  // s suffix is a std::string literal

    return 0;
}
--

=== Constexpr strings

If you try to define a constexpr std::string, your compiler will probably generate an error

